# Generated by Django 4.2.5 on 2023-09-09 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrip',
            name='trip_id',
        ),
        migrations.RemoveField(
            model_name='usertrip',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usertrip',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trip'),
        ),
        migrations.AddField(
            model_name='usertrip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
