# Generated by Django 4.2.5 on 2023-09-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='distance_metre',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='duration_second',
        ),
        migrations.AddField(
            model_name='trip',
            name='distance_kilometre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='elevation_gain_metre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='elevation_loss_metre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
